### ISSUE TITLE
satprep_patch_freeze.py not working for systems without base channel

### ISSUE THREAD

**Issue by novonilc** [stdevel/satprep#50]
```
$ ./satprep_patch_freeze.py -a auth -g Test_for_Patching
ERROR:satprep_patch_freeze:Unable to scan system 'dev-stmnt-app-02', check hostname and profile name!
ERROR:satprep_patch_freeze:Unable to scan system 'dev-stmnt-db-01', check hostname and profile name!
ERROR:satprep_patch_freeze:Unable to scan system 'dev-stmnt-idx-01', check hostname and profile name!
ERROR:satprep_patch_freeze:Unable to scan system 'dev-stmnt-app-03', check hostname and profile name!
ERROR:satprep_patch_freeze:Unable to scan system 'dev-stmnt-proxy-01', check hostname and profile name!
ERROR:satprep_patch_freeze:Unable to scan system 'dev-stmnt-db-02', check hostname and profile name!
ERROR:satprep_patch_freeze:Unable to scan system 'dev-stmnt-app-01', check hostname and profile name!
Traceback (most recent call last):
  File "./satprep_patch_freeze.py", line 313, in <module>
    main(options)
  File "./satprep_patch_freeze.py", line 237, in main
    remapSystems(client, key)
  File "./satprep_patch_freeze.py", line 165, in remapSystems
    else: myNewBase = options.targetLabel+"-"+options.targetDate+"."+myBase["label"]
KeyError: 'label'
```

**Comment by novonilc** [comment]
This error only comes if the machine is not subscribed to any channels

**Comment by stdevel** [comment]
Is cloning channels now working for you? (see also issue #46)

**Comment by novonilc** [comment]
Its working still not able to clone some channels and got errors as before

Sent from my Iphone




On Mon, Dec 21, 2015 at 7:16 AM -0800, "Christian Stankowic" <notifications@github.com> wrote:












Is cloning channels now working for you? (see also issue #46)

**Comment by stdevel** [comment]
Added a workaround for hosts without valid base channel. Checked this in my lab - is this also working for you?

**Comment by novonilc** [comment]
No still not working. I got this with your latest code.

**Comment by novonilc** [comment]
ohh ok hold on i will check now with your latest commit

**Comment by novonilc** [comment]
Yes its working...Thanks
