### ISSUE TITLE
Temporarily disable DRS / Storage DRS for satprep_wa_vcvms.py

### ISSUE THREAD

**Issue by stdevel** [stdevel/satprep#53]
The script `satprep_wa_vcvms.py` crashes if a VM was moved to another host or storage once it started:

```
INFO:satprep_wa_vcvms:Checked 270 of 527 VMs so far...
Traceback (most recent call last):
  File "./satprep_wa_vcvms.py", line 251, in <module>
    main(options)
  File "./satprep_wa_vcvms.py", line 95, in main
    thisVM = myVC.get_vm_by_path(vm)
  File "/usr/lib/python2.6/site-packages/pysphere-0.1.8-py2.6.egg/pysphere/vi_server.py", line 291, in get_vm_by_path
    FaultTypes.OBJECT_NOT_FOUND)
pysphere.resources.vi_exception.VIException: [Object Not Found]: Could not find a VM with path '[Prod 01] MYSRV/MYSRV.vmx'
```

It would be great if the script checks the used clusters and storage clusters first and temporarily disables automatic load-balancing.

**Comment by stdevel** [comment]
It might be necessary to switch to the Python library **pyvmomi** for this: https://github.com/vmware/pyvmomi

**Comment by stdevel** [comment]
Won't do this as I started rewriting this toolkit.
